data:
    url: https://archive.ics.uci.edu/static/public/45/heart+disease.zip
    dataset_name: heart_disease.zip
    target_dir: data/
load:
    target_file: processed.cleveland.data
    column_names: ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'nums']
    target_col: "nums"
    test_size: 0.2
    random_state: 42