name: DVC Data Pull

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  pull-data:
    runs-on: ubuntu-latest

    env:
      # MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      # MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USER_NAME }}
      # MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      DAGSHUB_USER_NAME: ${{ secrets.DAGSHUB_USER_NAME }}
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install DVC
        run: uv tool install dvc

      - name: Configure DVC Secrets
        run: |
          # Use --local to ensure credentials aren't committed to the runner's git state
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user ${{ secrets.DAGSHUB_USER_NAME }}
          dvc remote modify origin --local password ${{ secrets.DAGSHUB_TOKEN }}

      - name: Pull Data from DVC
        run: |
          dvc pull data/heart_disease.zip.dvc -r origin

      - name: Install Test Dependencies
        run: uv sync --group test

      - name: Sanity Test
        run: uv run pytest tests/

      - name: Install Dependencies
        run: uv sync

      - name: Preprocess
        run: dvc repro

      - name: Report Metrics
        run: |
          echo "## Model Performance Summary" >> $GITHUB_STEP_SUMMARY
          echo "### Metrics" >> $GITHUB_STEP_SUMMARY
          cat metrics.json | jq -r 'to_entries | .[] | "- **\(.key)**: \(.value)"' >> $GITHUB_STEP_SUMMARY